name: easy_lut
description: Dart package to easily apply LUT for images
repository: https://github.com/jkirtyan-dev/easy_lut.git
homepage:
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  image: ^4.0.10

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
