name: easy_lut
description: Dart package to easily apply LUT for images. You can use LUT files with 1, 3 or 6 columns of data.
repository: https://github.com/jkirtyan-dev/easy_lut.git
homepage:
version: 0.2.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  image: ^4.0.10

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
